### 1. Numpy Gradient Descent

In [ ]:
#Numpy Gradient Descent

import numpy as np
import matplotlib.pyplot as plt

# 재현성을 위해서 seed 고정
np.random.seed(42)

# x 데이터 생성
x = np.linspace(0,10,100) #0부터 10까지 100개의 점

# 실제 정답 함수: y = 3x+2+noise

true_w = 3.0
true_b = 2.0
noise = np.random.randn(100) * 2.0

y = true_w + true_b + noise

# 데이터 확인
plt.scatter(x,y,alpha=0.7)
plt.xlabel("x")
plt.ylabel("y")
plt.title("Training Data")
plt.show()

In [ ]:
# 손실함수 정의
def mse_loss(y_true, y_pred):
    return np.mean((y_true - y_pred)**2)

# gradient Descent 한번의 업데이트
def compute_gradients(x, y, w, b):
    n = len(x)
    y_pred = x * w + b

    # 오차
    error = y_pred - y
    # 미분 결과
    dw = (2/n) * np.sum(error*x)
    db = (2/n) * np.sum(error*1)
    return dw, db

# 전체 학습 루프
def gradient_descent(x, y, lr=0.01, epochs=1000):
    # parameter 초기화
    w = 0.0
    b = 0.0

    # loss 기록용
    loss_history = []

    for epoch in range(epochs):
        # 예측
        y_pred = w * x + b
        # loss 계산
        loss = mse_loss(y, y_pred)
        loss_history.append(loss)

        # gradient 계산
        dw, db = compute_gradients(x, y, w, b)

        # parameter 업데이트
        w = w - lr * dw
        b = b - lr * db

        # 중간 출력
        if epoch % 100 ==0:
            print(f"epoch = {epoch:4d}, loss = {loss:.6f}, w={w:.4f},b={b:.4f}")
    return w,b,loss_history


In [ ]:
# 학습 실행
w, b, loss_history = gradient_descent(x, y, lr = 0.01, epochs = 1000)
print("최종 결과")
print("w=", w)
print("b=",b)

# 그래프 출력
plt.plot(loss_history)
plt.xlabel("Epoch")
plt.ylabel("MSE Loss")
plt.title("Loss Curve")
plt.show()

# 학습된 직선 그리기
y_pred = w * x +b

plt.scatter(x,y,alpha=0.6, label="Data")
plt.plot(x,y_pred, linewidth=2, label='Fitted Data')
plt.xlabel("x")
plt.ylabel("y")
plt.title("Linear regression with Gradient Descent")
plt.legend()
plt.show()

#### 과제 1. 다변수 선형회귀의 Gradient Descent 확장해보기

$$
\hat{y} = w_1x_1 + w_2x_2+w_3x_3 + \cdots + w_nx_n
$$

이 경우에 Numpy로 구현해볼것.
(hint: numpy의 @)

### 2. SGD (Stochastic(sample) Gradient Descent)

In [ ]:
#SGD(Stochastic(sample) Gradient Descent)

# 전체 학습 루프
def stochastic_gradient_descent(x,y,lr=0.001, epochs=100):

    # 파라미터 초기화
    w = 0.0
    b = 0.0
    n = len(x)

    #loss 기록용
    loss_history = []

    for epoch in range(epochs):
        indices = np.random.permutation(n)
        x_shuffled = x[indices]
        y_shuffled = y[indices]

        for i in range(n):
            xi = x_shuffled[i]
            yi = y_shuffled[i]
            # 예측
            y_pred = w * xi +b

            # 오차
            error = y_pred - yi

            # gradient 계산
            dw = 2 * error *xi
            db = 2 * error

            #파라미터 업데이트
            w = w - lr * dw
            b = b - lr * db

            #epoch이 끝난 후 전체 loss기록
            total_pred = w*x+b
            loss = np.mean((y-total_pred) **2)
            loss_history.append(loss)

            # 중간 출력
            if epoch % 10 ==0:
                print(f"epoch = {epoch:3d}, loss = {loss:.6f}, w={w:.4f},b={b:.4f}")
    return w,b,loss_history


In [ ]:
# 학습 실행
w, b, loss_history = stochastic_gradient_descent(x, y, lr = 0.01, epochs = 1000)
print("최종 결과")
print("w=", w)
print("b=",b)

### 3. Pytorch
1. 텐서 연산
 - Numpy 배열처럼 다차원 배열을 다룸.
 - 하지만 GPU를 쓸 수 있음. (Numba)
Polars(https://pola.rs/)

2. 자동미분(autograd)
- 손실함수를 기준으로 미분값(gradient)을 자동으로 구함.

In [ ]:
#pip install torch torchvison torchaudio
import torch
print(torch.__version__)    # 2.11.0+cpu

# GPU 방법 확인
device = torch.device("cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu")
print("Using device:", device)

# pytorch는 텐서로 작동하기때문에 GPU로 돌리는 게 좋다.

In [25]:
# Tensor는 pytorch의 핵심 객체
## Tensor는 다차원 배열

import torch
a = torch.tensor(3.0) # 스칼라
b = torch.tensor([1.0,2.0,3.0]) #벡터
c = torch.tensor([[1,2],[3,4]]) # 행렬

print(a)
print(b)
print(c)

x = torch.tensor([[1,2,3],
                 [4,5,6]])

print(x.shape)      # (2, 3)인 행렬
print(x.dim)        # <built-in method dim of Tensor object at 0x000001CA953E93B0> <- 메모리주소
print(x.ndim)       # 2차원이다.


tensor(3.)
tensor([1., 2., 3.])
tensor([[1, 2],
        [3, 4]])
torch.Size([2, 3])
<built-in method dim of Tensor object at 0x000001CA953E93B0>
2


In [ ]:
# 인덱싱과 슬라이싱 = 거의 numpy와 비슷
x = torch.tensor([[10,20,30],
                 [40,50,60]])

print(x[0,0])   # 10(1행x1열)
print(x[0,2])   # 30(1행x3열)
print(x[1])     # 2행 [40,50,60]
print(x[:,1])   # 2열 [20,50]
print(x[:,:2])  # 1행x1열, 2열

In [30]:
# 원소별 연산 (element-wise 연산)
## 각 위치마다 연산을 진행함

### [1,2,3] * [4,5,6] = [4,10,18]
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

# 행렬 곱
A = torch.tensor([[1.0,2.0],
                 [3.0,4.0]])
B = torch.tensor([[5.0,6.0],
                 [7.0,8.0]])
print(torch.matmul(A,B))        
print(A @ B)

tensor([5, 7, 9])
tensor([-3, -3, -3])
tensor([ 4, 10, 18])
tensor([0.2500, 0.4000, 0.5000])
tensor([[19., 22.],
        [43., 50.]])
tensor([[19., 22.],
        [43., 50.]])


In [ ]:
# unsqueeze: 차원을 하나 추가하는 것
# 배치 차원을 추가할때 많이 사용함.
x = torch.tensor([1.0,2.0,3.0])
print(x.shape)       #[3]

y = x.unsqueeze(0)
print(y.shape)       #[1,3]

z = x.unsqueeze(1)
print(z.shape)       #[3,1]

#squeeze #크기가 1인 차원을 제거.
x = torch.tensor([[1.0,2.0,3.0]])
print(x.shape)       #[1,3]

y = x.squeeze()
print(y.shape)

In [38]:
# autograd: 자동미분
## requires_grad = True -> 텐서에 대해 gradient 추적
import torch

x = torch.tensor(2.0, requires_grad=True)
## 2.0 -> 값이 2.0인 스칼라 텐서를 생성
## requires_grad=True -> 텐서에서 이루어지는 모든 연산을 추적하도록 설정
## 이를 통해 나중에 이 변수에 대한 미분값($\frac{dy}{dx}$)을 자동으로 계산
y = x**2 +3*x+1

print(y)        # x에 2.0 대입
y.backward()    # 자동 미분의 핵심 $y$를 기준으로 역방향(Backward) 미분을 수행 y` = 2x+3
print(x.grad)

RuntimeError: Only Tensors of floating point and complex dtype can require gradients

In [32]:
# 선형회귀를 Pytorch로 구현
import torch
import torch.nn as nn
import torch.optim as optim

# 데이터 만들기
x = torch.tensor([[1.0],[2.0],[3.0],[4.0]])
y = torch.tensor([[3.0],[5.0],[7.0],[9.0]]) # y=2x+1

# 모델 정의
model = nn.Linear(1,1)
# nn.Linear(데이터 개수, 특성 개수) -> hat{y} = W(가중치)x + b(편향, bias)

#손실함수, 옵티마이저
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)  #model.parameters(): 학습할 파라미터

for epoch in range(1000):
    y_pred = model(x)

    loss = criterion(y_pred,y)

    #gradient 초기화
    optimizer.zero_grad()   # 이전 gradient 제거

    #역전파
    loss.backward()         # 현재 loss 기준으로 gradient 계산

    # 파라미터 업데이트
    optimizer.step()        # gradient를 이용해 파라미터 업데이트

    if epoch % 100 == 0:
        print(f"epoch={epoch}, loss={loss.item():.6f}")
print("학습된 weight", model.weight.item())
print("학습된 bias", model.bias.item())


epoch=0, loss=31.899670
epoch=100, loss=0.114002
epoch=200, loss=0.062586
epoch=300, loss=0.034359
epoch=400, loss=0.018863
epoch=500, loss=0.010355
epoch=600, loss=0.005685
epoch=700, loss=0.003121
epoch=800, loss=0.001713
epoch=900, loss=0.000941
학습된 weight 2.0189123153686523
학습된 bias 0.9443954825401306


In [ ]:
# 추론
new_x = torch.tensor([[5.0]])

model.eval()
with torch.no_grad():       # 평가나 추론할 때는 gradient 값이 필요 없어서 메모리 절약, 계산 속도가 향상
    pred = model(new_x)
print("x=5일때 예측값:", pred.item())

In [ ]:
# 간단한 MLP

import torch
import torch.nn as nn

class SimpleMLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(2,4)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(4,1)
    def forward(self,x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        return x

In [37]:
# Dataset과 Dataloader
## 데이터가 많아지면 한 번에 넣지 않고, batch를 나눠 학습함.

from torch.utils.data import TensorDataset, DataLoader
import torch

x = torch.tensor([[1.0],[2.0],[3.0],[4.0],[5.0],[6.0]])
y = torch.tensor([[3.0],[5.0],[7.0],[9.0],[11.0],[13.0]])

dataset = TensorDataset(x,y)
loader = DataLoader(dataset,batch_size=2, shuffle=True)

for batch_x, batch_y in loader:
    print("batch_x:", batch_x)
    print("batch_y:", batch_y)
    print('***'*10)

batch_x: tensor([[4.],
        [2.]])
batch_y: tensor([[9.],
        [5.]])
******************************
batch_x: tensor([[1.],
        [6.]])
batch_y: tensor([[ 3.],
        [13.]])
******************************
batch_x: tensor([[3.],
        [5.]])
batch_y: tensor([[ 7.],
        [11.]])
******************************


#### Q1. 데이터들이 실수형인 이유가 있나요?
- 기울기(Gradient)를 계산하여 가중치를 미세하게 조정해야하고, 모델의 가중치($W$)와 편향($b$)을 업데이트하려면 데이터와 연산 결과가 반드시 실수 형태여야 한다.
- RuntimeError: Only Tensors of floating point and complex dtype can require gradients
- 실수형이나 복소수형 텐서만 기울기를 가질 수 있다.


### 4. Seq2Seq
- 입력 시퀀스를 뒤집어서 출력하기
    - 입력: 1, 5, 3, 2
    - 출력: 2, 3, 5, 1

In [7]:
import torch
import torch.nn as nn
import torch.optim as optim
import random

device = torch.device("cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu")
print("Using device:", device)

Using device: cpu


In [56]:
PAD_TOKEN = "<PAD>"     # <PAD>: 길이를 맞추기 위한 패딩
SOS_TOKEN = "<SOS>"     # <SOS>: 디코더 시작 토큰
EOS_TOKEN = "<EOS>"     # <EOS>: 문장 끝 토큰

vocab = [PAD_TOKEN, SOS_TOKEN, EOS_TOKEN] + [str(i) for i in range(1,10)]
token_to_idx = {token:idx for idx, token in enumerate(vocab)}
idx_to_token = {idx:token for token, idx in token_to_idx.items()}

PAD_IDX = token_to_idx[PAD_TOKEN]
SOS_IDX = token_to_idx[SOS_TOKEN]
EOS_IDX = token_to_idx[EOS_TOKEN]

print(token_to_idx)

{'<PAD>': 0, '<SOS>': 1, '<EOS>': 2, '1': 3, '2': 4, '3': 5, '4': 6, '5': 7, '6': 8, '7': 9, '8': 10, '9': 11}


In [57]:
# 샘플 하나 생성하는 함수
## 길이 3~6정도의 랜덤 숫자 시퀀스를 만드는 함수
def generate_sample(min=3, max=6):
    length = random.randint(min, max)
    seq = [str(random.randint(1,9)) for _ in range(length)]

    src = [token_to_idx[token] for token in seq]
    tgt = [token_to_idx[token] for token in reversed(seq)]

    return src,tgt

src, tgt = generate_sample()
print("src",src)
print("tgt",tgt)
print("src tokens:", [idx_to_token[i] for i in src])
print("tgt tokens:", [idx_to_token[i] for i in tgt])


src [5, 7, 11, 6]
tgt [6, 11, 7, 5]
src tokens: ['3', '5', '9', '4']
tgt tokens: ['4', '9', '5', '3']


In [58]:
# 데이터 셋 만들기
def build_dataset(num_samples=2000):
    data = []
    for _ in range(num_samples):
        src, tgt = generate_sample()

        # decorder input: [<SOS>, X, X, X]
        # decorder target: [X, X, X, <EOS>]
        decoder_input = [SOS_IDX] + tgt
        decoder_target = tgt + [EOS_IDX]

        data.append((src, decoder_input, decoder_target))
    return data

# 샘플 만들기
dataset = build_dataset(5)

for src, dec_in, dec_tgt in dataset:
    print("src:", [idx_to_token[x] for x in src])
    print("dec_input:", [idx_to_token[x] for x in dec_in])
    print("dec_tgt:", [idx_to_token[x] for x in dec_tgt])

src: ['6', '5', '3']
dec_input: ['<SOS>', '3', '5', '6']
dec_tgt: ['3', '5', '6', '<EOS>']
src: ['2', '5', '8']
dec_input: ['<SOS>', '8', '5', '2']
dec_tgt: ['8', '5', '2', '<EOS>']
src: ['6', '1', '2', '3']
dec_input: ['<SOS>', '3', '2', '1', '6']
dec_tgt: ['3', '2', '1', '6', '<EOS>']
src: ['9', '4', '2']
dec_input: ['<SOS>', '2', '4', '9']
dec_tgt: ['2', '4', '9', '<EOS>']
src: ['5', '3', '6', '4']
dec_input: ['<SOS>', '4', '6', '3', '5']
dec_tgt: ['4', '6', '3', '5', '<EOS>']


In [69]:
# 배치 처리를 하기 위한 padding 필요
# [1, 2, 3]
# [4, 5]    -> 배치 처리를 할 수 없음. 왜냐면? 길이가 같지 않으면 학습이 안됨.

# 시퀀스 길이가 다르면 안됨.
# 배치로 만들면 [4, 5, <PAD>]

def pad_seq(sequences, pad_value=PAD_IDX):
    max_len = max(len(seq) for seq in sequences)
    padded = []

    for seq in sequences:
        padded_seq = seq + [pad_value] * (max_len - len(seq))
        padded.append(padded_seq)
    return torch.tensor(padded, dtype=torch.long)

# 배치 생성 함수
def get_batches(data, batch_size = 32):
    random.shuffle(data)

    for i in range(0, len(data), batch_size):
        batch = data[i:i + batch_size]
        
        src_batch = [item[0] for item in batch]
        dec_input_batch = [item[1] for item in batch]
        dec_tgt_batch = [item[2] for item in batch]

        src_padded = pad_seq(src_batch, PAD_IDX).to(device)
        dec_input_padded = pad_seq(dec_input_batch, PAD_IDX).to(device)
        dec_tgt_padded = pad_seq(dec_tgt_batch, PAD_IDX).to(device)

        yield src_padded, dec_input_padded, dec_tgt_padded

        
        

In [64]:
## yield: 제너레이터(Generator)
## return: 함수의 실행을 끝내고 값을 반환
## yield: 함수의 상태를 그대로 유지한 채 밖으로 값을 전달
    ## 함수 내부 코드가 즉시 실행대신에 제너레이터 객체 반환
def number_gen():
    yield 1     # 여기서 멈추고 1을 반환
    yield 2     # 다시 호출하면 여기서 멈추고 2을 반환
    yield 3     # 다시 호출하면 여기서 멈추고 3을 반환
gen = number_gen()
print(next(gen))
print(next(gen))
print(next(gen))

# 왜 yield를 사용하는 가?
## 1. 메모리 효율성: 필요할 때만 숫자를 하나씩 생성하기 때문에 메모리를 거의 차지 하지 않음
## 2. 무한한 데이터 표현: 끝이 없는 데이터 스트림을 처리할 때 유용 (무한 루프) 
#     -> 안전한 값을 하나씩 내보낼 수 있음
## 3. 비동기 프로그래밍 및 중간 상태 유지: 함수의 지역 변수와 실행 상태가 보존되므로,
#     복잡한 로직 중간에 값을 내보내고 다시 돌아와서 작업하기 좋음

# 단점
## 1. 끝까지 순회하면 객체 사람짐
## 2. lengh를 사용할 수 없음 -> 데이터를 미리 만들어 놓지 않음

# 메모리 절약기 최우선인 대용량 데이터 처리에는 yield인데
# 여러번 가공하거나 일반적인 return이 훨씬 편리함.

1
2
3


In [70]:
# 배치 shape
train_data = build_dataset(100)

# shape: (batch_size, seq_len)
for src_batch, dec_input_batch, dec_tgt_batch in get_batches(train_data, batch_size=4):
    print("src_batch shape: ", src_batch.shape)
    print("dec_input_batch shape: ", dec_input_batch.shape)
    print("dec_tgt_batch shape: ", dec_tgt_batch.shape)
    break

src_batch shape:  torch.Size([4, 6])
dec_input_batch shape:  torch.Size([4, 7])
dec_tgt_batch shape:  torch.Size([4, 7])


### 5. Encoder
- 입력 시퀀스를 읽고 마지막 hidden stage(context vector)를 만들어 냄

In [8]:
# LSTM
class Encoder(nn.Module):
    def __init__(self, vocab_size, emb_dim, hidden_dim):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size,emb_dim, padding_idx=PAD_IDX)
        self.lstm = nn.LSTM(emb_dim, hidden_dim, batch_first=True)
    
    def forward(self,src):
        # src:(batch_size, src_len) / embedded: (batch_size, src_len, emb_dim)
        embedded = self.embedding(src)
        
        outputs, (hidden,cell) = self.lstm(embedded)
        # outputs: (batch_size, src_len,hidden_dim)
        # hidden: (1, batch_size, hidden_dim)
        # cell : (1,batch_size, hidden_dim)
        return hidden,cell
# outputs: 각 시점의 출력
# hidden,cell: 마지막 상태 -> Decoder는 보통 마지막 상태를 받아 시작.

### 6. Decoder


In [9]:
class Decoder(nn.Module):
    def __init__(self,vocab_size, emb_dim, hidden_dim):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, emb_dim, padding_idx = PAD_IDX)
        self.lstm = nn.LSTM(emb_dim, hidden_dim, batch_first=True)
        self.fc = nn.Linear(hidden_dim, vocab_size)

    def forward(self, x, hidden,cell):
        # x:(batch_size, ) or (batch_size,1)
        if x.dim() ==1:
            x = x.unsqueeze(1)
        # x:(batch_size,1)

        embedded = self.embedding(x)
        # embedded: (batch_size,1,emb_dim)

        output, (hidden,cell) = self.lstm(embedded, (hidden,cell))

        prediction = self.fc(output.squeeze(1))
        # prediction: (batch_size, vocab_size)
        # 각 토큰에 대한 점수(logits)

        return prediction, hidden,cell

In [10]:
class Seq2Seq(nn.Module):
    def __init__(self, encoder, decoder,device):
        super().__init__()
        self.encoder = encoder
        self.decoder = decoder
        self.device = device
    
    def forward(self, src, dec_input, teacher_forcing_ratio=1.0):
        # src: (batch_size, src_len)
        # dec_input: (batch_size, tgt_len)

        batch_size = src.size(0)
        tgt_len = dec_input.size(1)
        vocab_size = self.decoder.fc.out_features

        outputs = torch.zeros(batch_size, tgt_len, vocab_size).to(self.device)

        hidden, cell = self.encoder(src)

        x = dec_input[:,0] # 첫 입력은 <SOS>
        # dec_input: (batch_size, tgt_len)

        for t in range(tgt_len):
            #현재 입력(x)과 이전 시점의 상태(hidden,cell)를 디코더에 입력
            # prediction: 현재 시점의 단어 예측 값, hidden/cell: 다음 시점으로 전달할 상태
            prediction, hidden,cell = self.decoder(x, hidden,cell)

            # 예측된 결과를 전체 출력 텐서의 해당 시점(t)에 저장
            outputs[:,t,:] = prediction

            #Teach Forcing 적용 여부를 확률적으로 결정
            ## -> 모델의 예측값 대신에 정답 토큰을 다음 입력값으로 넣어주는 것
            ## random.random() 설정한 비율보다 작으면 True( 교사 강요 사용)
            teacher_force = random.random() < teacher_forcing_ratio

            if t+1 < tgt_len:
                # 다음 시점 (t+1)에 넣어줄 입력값(x)을 준비함. 단, 마지막 시점이 아니여야 함
                top1 = prediction.argmax(1)
                ## 모델이 예측한 값 중에서 가장 확율이 높은 단어의 인덱스를 추출

                x = dec_input[:,t+1] if teacher_force else top1
                # teacher_force가 True이면 실제 정답(dec_input)을 다음 입력으로 사용
                # False이면 모델이 방금 예측한 값(top1)을 다음 입력으로 사용
        return outputs
        #모든 시점의 예측이 담긴 텐서 반환            

In [ ]:
# 모델 생성
VOCAB_SIZE = len(vocab)
EMB_DIM = 32
HIDDEN_DIM = 64

encoder = Encoder(VOCAB_SIZE, EMB_DIM, HIDDEN_DIM)
decoder = Decoder(VOCAB_SIZE, EMB_DIM, HIDDEN_DIM)

model = Seq2Seq(encoder, decoder, device).to(device) 

In [ ]:
# LOSS함수와 Optimizer
criterion = nn.CrossEntropyLoss(ignore_index = PAD_IDX)
optimizer = optim.Adam(model.parameters(), lr=0.01)

In [ ]:
# 학습용, 테스트 데이터 준비
train_data = build_dataset(5000)
test_data = build_dataset(500)

# 학습 루프: optimizer 필요
def train_one_epoch(model, data, optimizer, criterion, batch_size=32):
    model.train()   # 모델을 학습 모드 설정(Dropout, Batch Normalization 비활성화)
    total_loss = 0  # 한 epoch마다 누적 손실을 기록하는 변

    # 데이터를 batch_size 크기 만큼 순회 (Source, Decorder Input, Decoder target)
    for src_batch, dec_in_batch, dec_tgt_batch in get_batches(data, batch_size):
        # 지난 배치에서 계산된 gradient를 0으로 초기화
        optimizer.zero_grad()


        outputs = model(src_batch, dec_in_batch, teacher_forcing_ratio=0.5)
        # outputs:(batch_size,tgt_len, vocab_size)
        # 모델에 데이터를 입력하여 예측값을 생성( 교사강요는 0.5 비율)

        vocab_size = outputs.size(-1)
        # 손실함수 계산을 위해서 단어장 크기(vocab_size) 추출
        # outputs: (batch_size, tgt_len, vocab_size) -> outputs.size(-1)

        outputs = outputs.reshape(-1, vocab_size)
        # (batch_size*tgt_len, vocab_size) -> crossEntropy가 2D텐서를 원함.
        dec_tgt_batch = dec_tgt_batch.reshape(-1)
        # 실제 정답(target)도 예측값과 짝을 맞추기 위해 1D 텐서로 변환

        loss = criterion(outputs, dec_tgt_batch)    # 예측값과 실제 정답 사이의 계산
        loss.backward()                             # 역전파 수행

        optimizer.step()                            #계산된 기울기 바탕으로 모델의 가중치 업데이트
        total_loss +=loss.item()                    # 현재 배치의 손실 값을 누적

    return total_loss / (len(data) / batch_size)    #전체 손식을 배치 수로 나누어 평균 손실을 반환

In [ ]:
# 평가함수: optimizer 불필요
def evaluate(model, data, criterion, batch_size=32):
    model.eval() # 모델을 학습모드 설정(Dropout, Batch Normalization 비활성화)
    total_loss = 0 

    with torch.no_grad():
        for src_batch, dec_in_batch, dec_tgt_batch in get_batches(data, batch_size):
            outputs = model(src_batch, dec_in_batch, teacher_forcing_ratio=0.0)

            vocab_size = outputs.size(-1)
            outputs = outputs.reshape(-1, vocab_size)
            dec_tgt_batch = dec_tgt_batch.reshape(-1)
            loss = criterion(outputs, dec_tgt_batch)
            total_loss +=loss.item()
    return total_loss / (len(data) / batch_size)


In [ ]:
# 추론 함수
# 학습 때와 달리 정답이 없기 때문에 모델이 직전 단계에서 예측한 단어를 다음 단계의 입력으로 사용하는 Autoregressive(자기회귀)방식
def predict(model, src_seq, max_len=10):
    model.eval() #모델을 평가 모드로 전환(Dropout, Batch Normalization 등을 비활성화)

    src_tensor = torch.tensor([src_seq], dtype=torch.long).to(device)
    # 입력 리스트(src_seq)를 2차원 텐서 [1, sequence_length]로 변환후 CPU/GPU 전송

    with torch.no_grad():
        #계산을 비활성화하여 메모리 사용량을 줄이고 속도를 높임
        hidden,cell = model.encoder(src_tensor)
        #입력 문장을 인코더에 넣어 문맥 정보가 담긴 hidden과 celll 상태를 추출

        x = torch.tensor([SOS_IDX], dtype=torch.long).to(device)
        # 디코더에 첫 번째 입력으로 사용할 <SOS> 토큰을 텐서로 생성
        generated = []
        #예측된 단어 인덱스를 저장할 리스트

        for _ in range(max_len):
            # 지정된 최대길이(max_len)만큼 반복하여 단어 생성
            prediction, hidden, cell = model.decoder(x, hidden,cell)
            # 현재 입력(x)과 상태(hidden, cell)를 디코더에 넣어 다음 단어 예측
            top1 = prediction.argmax(1).item()
            # 예측된 확률 분포에서 가장 높은 확률로 가진 단어의 인덱스를 숫자로 추출

            if top1 == EOS_IDX:
                # 모델의 문장의 끝을 알리는 <EOS> 토큰을 생성하면 반복 중단
                break
            generated.append(top1)
            #생성된 단어 인덱스를 결과 리스트에 저장
            x = torch.tensor([top1], dtype=torch.long).to(device)
    return generated

In [ ]:
# 결과 확인 함수
def decoder_indices(indices):
    return [idx_to_token[idx] for idx in indices]

for _ in range(10):
    src,tgt = generate_sample()
    pred = predict(model,src)

    print("입력:", decoder_indices(src))
    print("정답:", decoder_indices(tgt))
    print("예측:", decoder_indices(pred))
    print("-"*40)